# Build stage
FROM node:18-alpine AS build
WORKDIR /app

# Install dependencies. If package-lock.json is missing fall back to `npm install`.
# Copy package.json first to leverage Docker layer caching.
# Copy package files (will copy package-lock.json if present)
COPY package*.json ./
RUN if [ -f package-lock.json ]; then \
			npm ci --silent; \
		else \
			npm install --silent; \
		fi

# Copy source files
COPY public ./public
COPY src ./src

# Allow build-time injection of frontend env vars
ARG REACT_APP_API_URL
ARG REACT_APP_CHAT_URL
ARG REACT_APP_MODEL_SERVICE_URL
ARG REACT_APP_WXPAY_URL
ARG REACT_APP_GOBACK_URL
ARG REACT_APP_COZE_API_URL
ARG REACT_APP_COZE_TOKEN
ARG REACT_APP_COZE_BOT_ID_KEYWORD
ARG REACT_APP_COZE_BOT_ID_TEMPLATE
ARG REACT_APP_EXTENSION_DOWNLOAD_URL
ARG REACT_APP_XHS_BASE_URL
ARG REACT_APP_DOCS_URL
ARG REACT_APP_EXTENSION_TUTORIAL_URL
ARG REACT_APP_MESSAGE_PROGRAM_DOWNLOAD_URL
ARG REACT_APP_LOGIN_BG_IMAGE_URL
ARG REACT_APP_UPLOAD_FORMAT_IMAGE_URL
ARG NODE_MAX_OLD_SPACE_SIZE=768
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
ENV REACT_APP_CHAT_URL=${REACT_APP_CHAT_URL}
ENV REACT_APP_MODEL_SERVICE_URL=${REACT_APP_MODEL_SERVICE_URL}
ENV REACT_APP_WXPAY_URL=${REACT_APP_WXPAY_URL}
ENV REACT_APP_GOBACK_URL=${REACT_APP_GOBACK_URL}
ENV REACT_APP_COZE_API_URL=${REACT_APP_COZE_API_URL}
ENV REACT_APP_COZE_TOKEN=${REACT_APP_COZE_TOKEN}
ENV REACT_APP_COZE_BOT_ID_KEYWORD=${REACT_APP_COZE_BOT_ID_KEYWORD}
ENV REACT_APP_COZE_BOT_ID_TEMPLATE=${REACT_APP_COZE_BOT_ID_TEMPLATE}
ENV REACT_APP_EXTENSION_DOWNLOAD_URL=${REACT_APP_EXTENSION_DOWNLOAD_URL}
ENV REACT_APP_XHS_BASE_URL=${REACT_APP_XHS_BASE_URL}
ENV REACT_APP_DOCS_URL=${REACT_APP_DOCS_URL}
ENV REACT_APP_EXTENSION_TUTORIAL_URL=${REACT_APP_EXTENSION_TUTORIAL_URL}
ENV REACT_APP_MESSAGE_PROGRAM_DOWNLOAD_URL=${REACT_APP_MESSAGE_PROGRAM_DOWNLOAD_URL}
ENV REACT_APP_LOGIN_BG_IMAGE_URL=${REACT_APP_LOGIN_BG_IMAGE_URL}
ENV REACT_APP_UPLOAD_FORMAT_IMAGE_URL=${REACT_APP_UPLOAD_FORMAT_IMAGE_URL}
# Cap Node build memory to fit smaller servers.
ENV NODE_OPTIONS=--max-old-space-size=${NODE_MAX_OLD_SPACE_SIZE}
ENV CI=false
ENV GENERATE_SOURCEMAP=false
RUN npm run build

# Production stage: serve with nginx
FROM nginx:stable-alpine
# Remove default site config and add our nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy build artifacts
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
